apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
    auth_enabled: false
<<<<<<< HEAD
    schema_config:
      configs:
        - from: 2023-01-01
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb:
        directory: /data/loki/index

      filesystem:
        directory: /data/loki/chunks
=======
>>>>>>> 1446bdbba8e6c815032ce187d110549d3a5af916
