apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    name: prometheus-configmap
data:
  prometheus.yml: |-
      global:
        scrape_interval: 5s
        evaluation_interval: 5s
      scrape_configs:
      - job_name: node-exporter
        static_configs:
        - targets: ['10.0.16.58:9100']
      - job_name: prometheus
        static_configs:
        - targets: ['localhost:9090']
