apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail-sa
      containers:
        - name: promtail
          image: grafana/promtail:main
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/promtail
            - name: positions-volume
              mountPath: /run/promtail
      volumes:
        - name: config-volume
          configMap:
            name: promtail-config
        - name: positions-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: promtail-service
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 30180
  selector:
    app: promtail