apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_address: 127.0.0.1
      http_listen_port: 9080
    positions:
      filename: /run/promtail/positions.yaml
    clients:
      - url: http://10.0.16.89:31000/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_promtail_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_promtail_io_path]
            target_label: __path__
            replacement: $1
            action: replace
        pipeline_stages:
          - docker: {}
          - match:
              selector: '{job="kubernetes-pods"}'
            stages:
              - regex:
                  expression: '^(?:[^ ]* ){3}\[(?P<level>[^\]]*)\]'
          - labels:
              level: